In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from pathlib import Path
from scipy import misc
from sklearn import cluster
from sklearn.model_selection import train_test_split

FLATTENED_FILEPATH = "processed/flattened.csv"

processed_file = Path(FLATTENED_FILEPATH)
if processed_file.is_file():
    print("Loading Flattened Image...")
    flattened = np.loadtxt(FLATTENED_FILEPATH, delimiter=",")
    print("Finished Loading Flattened Image!")
else:
    print("Preprocessing Flattened Image...")
    
    images = np.empty([20, 512, 512, 3])
    %matplotlib inline
    
    for i in range(20):
        images[i] = misc.imread(('imgs/out%d.png') % (i+1))
        #images[i] = np.ones(images.shape[1:]) - images[i]
    flattened = np.empty([20*512*512, 3])
    for i in range(20):
        for x in range(512):
            for y in range(512):
                index = y + 512*(x + 512*i)
                flattened[index] = images[i, x, y]
    os.makedirs(os.path.dirname(FLATTENED_FILEPATH), exist_ok=True)
    np.savetxt(FLATTENED_FILEPATH, flattened, delimiter=",")
    print("Finished Preprocessing Flattened Image!")

Loading Flattened Image...


Finished Loading Flattened Image!


In [7]:
dbscan = cluster.KMeans(3)
dbscan.fit(flattened)

colors = dbscan.cluster_centers_

print("Selected colors:")
print(colors)

for i in range(20):
    for x in range(512):
        for y in range(512):
            index = y + 512*(x + 512*i)
            result = dbscan.predict([flattened[index]])
            images[i, x, y] = colors[result]
    misc.imsave(("results/res%d.png" % i), images[i])

Selected colors:
[[  75.73094772  134.70560519  133.13716105]
 [  95.71444988  165.10463133  157.43248274]
 [  62.13083329   88.8253934    89.66990263]]
